apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    cluster: cluster1
    environment: production
  annotations:
    cluster: cluster1
    region: us-west-2
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
