apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate the ConfigMap with the specified configuration
configMapGenerator:
  - name: toolkit-config
    files:
      - config.yaml

generatorOptions:
  disableNameSuffixHash: true
