apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

# Resources to include
resources:
- configmap.yaml
- deployment.yaml

# Common labels for all resources
commonLabels:
  app: prometheus
  component: monitoring
  app.kubernetes.io/part-of: monitoring-stack

# Configure the Prometheus deployment
patches:
- target:
    kind: Deployment
    name: prometheus
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/0
      value: --config.file=/etc/prometheus/prometheus.yml
    - op: add
      path: /spec/template/spec/volumes/0/name
      value: config-volume
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/0/name
      value: config-volume
