apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: toolkit-config
    files:
      - config.yaml

namespace: monitoring

generatorOptions:
  disableNameSuffixHash: true
