persistence:
  enabled: true
  storageClassName: hs-storage
  size: 5Gi

service:
  type: NodePort
  nodePort: 32000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki.hammerspace.svc.cluster.local:3100
        access: proxy
        isDefault: true
        
      - name: Prometheus
        type: prometheus
        url: http://prometheus.hammerspace.svc.cluster.local:9090
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          timeInterval: "15s"

adminUser: admin
adminPassword: admin123

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards/default