apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: hammerspace
  labels:
    app: loki
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3100
      targetPort: http
    - name: grpc
      protocol: TCP
      port: 9095
      targetPort: grpc
  selector:
    app: loki
