apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      # Scrape Vector metrics
      - job_name: 'vector'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - monitoring
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod_name

      # Cluster IP targets
      - job_name: 'boston_cluster_ips'
        static_configs:
          - targets:
              - '10.200.120.200:9101'  # API
              - '10.200.120.200:9102'  # C-Metrics
              - '10.200.120.200:9103'  # cAdvisor
              - '10.200.120.200:9100'  # Node Exporter
            labels:
              cluster: 'boston'
              instance: 'boston_cluster_ip'
              node_type: 'cluster_ip'
      
      # Anvil node: kbk-boston-anvil-1
      - job_name: 'boston_anvil_nodes'
        static_configs:
          - targets: [
              '10.200.120.201:9100'  # Node Exporter            ]
            labels:
              cluster: 'boston'
              instance: 'kbk-boston-anvil-1'
              node_type: 'anvil'
      # Dsx node: kbk-boston-dsx-1
      - job_name: 'boston_dsx_nodes'
        static_configs:
          - targets: [
              '10.200.120.202:9100'  # Node Exporter,
              '10.200.120.202:9102'  # DSX specific            ]
            labels:
              cluster: 'boston'
              instance: 'kbk-boston-dsx-1'
              node_type: 'dsx'
