# Cluster configurations
clusters:
  boston:
    cluster_ip: 10.200.120.200
    nodes:
      - type: anvil
        ip: 10.200.120.201
        name: kbk-boston-anvil-1
      - type: dsx
        ip: 10.200.120.202
        name: kbk-boston-dsx-1
  
  # Example second cluster (uncomment to use)
  # london:
  #   cluster_ip: 10.200.120.210
  #   nodes:
  #     - type: anvil
  #       ip: 10.200.120.211
  #       name: kbk-london-anvil-1
  #     - type: dsx
  #       ip: 10.200.120.212
  #       name: kbk-london-dsx-1

# Global settings
global:
  namespace: monitoring
  
  # Prometheus configuration
  prometheus:
    scrape_interval: 15s
    evaluation_interval: 15s
    retention: 7d
    storage_size: 10Gi
    
    # Port configuration
    ports:
      metrics: 9100
      api: 9101
      node_exporter: 9100
      c_metrics: 9102
      c_advisor: 9103

# Optional: Authentication credentials
auth:
  username: admin
  # password: ${HS_PASSWORD}  # Will be read from environment variable

# Dashboard configuration
dashboard:
  port: 8080
  theme: dark
