apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include Prometheus resources
resources:
  - service-account.yaml
  - service-monitor.yaml
  - deployment.yaml

# Labels for Prometheus resources
labels:
  - pairs:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/name: prometheus

# Name prefix for resources
namePrefix: prometheus-

# Disable name suffix hashes for ConfigMaps
generatorOptions:
  disableNameSuffixHash: true

# Generate the ConfigMap with the Prometheus configuration
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=generated-prometheus.yml
