apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    release: monitoring
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/name: prometheus
  endpoints:
  - port: http
    interval: 15s
    scrapeTimeout: 10s
    path: /metrics
  namespaceSelector:
    matchNames:
    - monitoring
