apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-prometheus
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: monitoring-stack
    app.kubernetes.io/version: "1.0"
