apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Import the base configuration
resources:
- ../../

# Override the namespace for this cluster
namespace: monitoring-cluster1

# Override variables for this cluster
configMapGenerator:
- name: prometheus-config
  behavior: merge
  literals:
    - TARGET_NAMESPACE=hammerspace
    - CLUSTER_NAME=cluster1

# Add cluster-specific labels
commonLabels:
  cluster: cluster1

# Add any cluster-specific patches here
patches:
- target:
    kind: Deployment
    name: prometheus
  patch: |-
    - op: add
      path: /spec/template/metadata/labels/cluster
      value: cluster1
