# RBAC for Controller
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner
rules:
  - apiGroups: [""]
    resources:
      [
        "pods",
        "persistentvolumes",
        "persistentvolumeclaims",
        "nodes",
        "events",
        "endpoints",
        "secrets",
      ]
    verbs: ["list", "watch", "get", "create", "delete", "update", "patch"]
  - apiGroups:
      ["storage.k8s.io", "snapshot.storage.k8s.io", "apiextensions.k8s.io"]
    resources:
      [
        "storageclasses",
        "volumeattachments",
        "volumeattachments/status",
        "volumesnapshotcontents/status",
        "volumesnapshots",
        "volumesnapshotcontents",
        "volumesnapshotclasses",
        "customresourcedefinitions",
      ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]