apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: hammerspace
  labels:
    app: vector
spec:
  type: NodePort
  selector:
    app: vector
  ports:
    - name: syslog-tcp
      protocol: TCP
      port: 5140
      targetPort: 5140
      nodePort: 32424
    - name: syslog-udp
      protocol: UDP
      port: 5140
      targetPort: 5140
      nodePort: 32424
    - name: api
      port: 8686
      targetPort: 8686
      protocol: TCP
